# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'NBAApiTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'SDWebImage'
  pod 'PKHUD'
  pod "Pastel"
  pod 'Stellar', :git => 'https://github.com/AugustRush/Stellar.git'
  pod 'Charts', '3.2.0'
  pod 'ScrollableDatepicker'
  # Pods for NBAApiTest

end
